---
format: 
  html:
    toc: true
    toc-depth: 3
    embed-resources: true
editor_options: 
  chunk_output_type: console
params:
  county: county
---

```{r, set-up, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 600, fig.width = 8)

library(dplyr)
library(DT)
library(here)
library(ggplot2)
library(leaflet)
library(lubridate)
library(qaqcmar)
library(readr)
library(sensorstrings)
library(stringr)
library(strings)
library(tidyr)

source(here("functions/subchunkify.R"))

theme_set(theme_light())

county <- params$county
#county <- "Halifax"

dt_options <- list(
      dom = 'ft',
      paging = FALSE,
      searching = TRUE,
      scrollY = "500px",
      pageLength = 500,
      columnDefs = list(list(className = 'dt-center', targets = "_all"))
)
```

```{r, import-data}
#| message: FALSE

# read in county data
dat <- import_strings_data(
  input_path = here("data-raw"),
  county = county,
  add_county_col = FALSE
) %>%
  filter(VARIABLE == "Dissolved Oxygen", UNITS == "percent saturation") %>% 
  ss_reformat_old_data() %>% 
  select(-c(waterbody, lease, latitude, longitude, mooring_type))
  
#ss_ggplot_variables(dat_all) 

# calculate thresholds based on the climatology
# user_thresh <- read_csv(
#   here("data/summary_filtered_shallow_do_data.csv"), show_col_types = FALSE
# ) %>% 
#   #filter(group == "all_month") %>% 
#   filter(
#     group == "county_month",
#      county == !!county
#     ) %>%
#   rename(mean_month = mean) %>% 
#   group_by(county) %>% 
#   summarise(
#     mean = round(mean(mean_month), digits = 3),
#     stdev = round(sd(mean_month), digits = 3)
#   ) %>% 
#   mutate(
#     qc_test = "grossrange",
#     variable = "dissolved_oxygen_percent_saturation",
#     user_min = mean - 3 * stdev, 
#     user_max = mean + 3 * stdev
#   ) %>% 
#   select(qc_test, county, variable, user_min, user_max) %>% 
#   pivot_longer(
#     cols = c("user_min", "user_max"), 
#     names_to = "threshold", values_to = "threshold_value"
#   )

user_thresh <- data.frame(
  qc_test = "grossrange",
     variable = "dissolved_oxygen_percent_saturation",
     user_min = 80, 
     user_max = 120
)

# make threshold table
thresh <- threshold_tables %>% 
  filter(variable == "dissolved_oxygen_percent_saturation", qc_test == "grossrange") %>% 
  bind_rows(user_thresh) %>% 
  pivot_wider(names_from = "threshold", values_from = "threshold_value")


#grossrange_table <- thresh

# apply grossrange test
dat_qc <- qc_test_grossrange(dat, grossrange_table = thresh) %>%
  group_by(station, deployment_range) %>%
  mutate(depl_id = cur_group_id()) %>%
  ungroup()

# summarise flagged observations
qc_summary <- dat_qc %>%
  rename(grossrange_flag = grossrange_flag_dissolved_oxygen_percent_saturation) %>%
  qc_assign_flag_labels() %>%
  group_by(deployment_range, station, grossrange_flag) %>%
  summarise(flag_count = n()) %>%
  mutate(flag_percent = round((100 * flag_count / sum(flag_count)), digits = 3)) %>%
  ungroup() %>%
  select(-flag_count) %>%
  pivot_wider(names_from = "grossrange_flag", values_from = "flag_percent") %>%
  arrange(station, deployment_range)
```

# `r county` QC Flags: Dissolved Oxygen, Grossrange

`r Sys.Date()`

# Gross Range Table

- user thresholds based on *climatology*

```{r}
# display thresholds used
thresh %>% 
  select(-c(county, month)) %>% 
  datatable(
    options = list(
      dom = 'ft', paging = FALSE, searching = FALSE,
      columnDefs = list(list(className = 'dt-center', targets = "_all"))
    ), 
    rownames = FALSE
  )
```

# Summary Table

Percent of observations in each deployment assigned with each qc flag. 

```{r}
datatable(qc_summary, options = dt_options, rownames = FALSE)
```

# Figures

```{r, body} 
#| results: 'asis'
#| message: FALSE

if("Suspect/Of Interest" %in% colnames(qc_summary)) {
  
  depl_id <- qc_summary %>%
    filter(!is.na(`Suspect/Of Interest`)) %>% 
    distinct(deployment_range, station) 
  
  stations <- unique(depl_id$station)
  
  for(i in seq_along(stations)){
    
    station_i <- stations[i]
    
    deployments <- depl_id %>% filter(station == station_i)
    deployments <- deployments$deployment_range
    
    cat('\n##', station_i, '\n')
    
    cat('\n')
    
    # plot for each deployment
    for(j in 1:length(deployments)){
      
      depl_j <- deployments[j]
      
      # subset data to station of interest
      dat_j <- dat_qc %>%
        filter(station == station_i, deployment_range == depl_j) %>%
        ss_convert_depth_to_ordered_factor()
      
      # height of figure j
      n_depth <- length(unique(dat_j$sensor_depth_at_low_tide_m))
      
      if(n_depth == 1) h = 2.75
      if(n_depth > 1) h = 2.75 * n_depth
      
      p <- qc_plot_flags(dat_j, qc_tests = "grossrange", ncol = 1)
      #p <- p$dissolved_oxygen_percent_saturation
      
      cat('\n###', depl_j, '\n')
      
      subchunkify(p$dissolved_oxygen_percent_saturation$grossrange, fig_height = h, fig_width = 8.5)
      
      #cat(paste("Figure ", k, ": ", station.j, fig.caption,  sep = ""), '\n')
      
      cat('\n')
    }
  }
}

```
